### ISSUE TITLE
code blocks turn black

### ISSUE THREAD

**Issue by datawrangl3r** [gethugothemes/liva-hugo#39]
The code blocks are turning black in the frontend as shown below.

The following image is for a bash code block in markdown given as:

```bash
> sudo apt-get install mysql-server
> sudo service mysql start
```

![livo issue](https://user-images.githubusercontent.com/29449969/103228401-c2413300-4956-11eb-9733-4957dc65407c.png)

**Comment by somratpro** [comment]
Hello @datawrangl3r 

We are using Hugo's default syntax highlighter in this template. so I suggest you ask this query in [Hugo forum](https://discourse.gohugo.io/). thank you

**Comment by somratpro** [comment]
Hey @datawrangl3r 

I think your issue has been solved. so I am closing this issue, if you have any more queries you can re-open this issue or create a new one. thank you

**Comment by hacback17** [comment]
Hi @datawrangl3r, I am facing the same issue. Would you please help me fix the issue if you could resolve it?

**Comment by rochefort** [comment]
I'm facing same issue.

**Comment by tfsomrat** [comment]
try this in config.toml

[markup.highlight]
style = 'manni' # see https://xyproto.github.io/splash/docs/all.html

**Comment by francofgp** [comment]
The solution that I found was the following:
In the file **_main.scss** modife the next line

´´´css

code {
    padding: 3px 5px;
    background: $gray;
    border: 1px solid $border-color;
    border-radius: 3px;
    /* color: $text-color-dark;    Comment out or Delete this line, or change Color*/ 
  }

´´´
