### ISSUE TITLE
Error on local

### ISSUE THREAD

**Issue by hvitis** [gethugothemes/liva-hugo#47]
Hi,

I am getting:

```
Error: module "bookworm-light" not found; either add it as a Hugo Module or store it in "XXXXX".: module does not exist
```

I am quite new to GoHugo. Does this repo mean that I can have the liva template as it is on the official page for free (just without those perks)?

The current state I arrive to is this:
<img width="990" alt="Screenshot 2021-10-15 at 02 14 48" src="https://user-images.githubusercontent.com/17104239/137412364-46a34dc6-6f64-4cb7-9d90-0fa1687536df.png">

**Comment by tfsomrat** [comment]
Hello @hvitis 

First of all, it's liva-hugo repository, and you are talking about bookworm theme. did you pull the bookworm theme in liva-hugo? I am confused. If you want bookworm theme, then please do a clean download from bookworm theme, and follow the installation guide provided in the readme file.  I am closing this issue. if you still face any issues, create a new one. thank you
